### ISSUE TITLE
Note App #1: Input Field and Submit

### ISSUE THREAD

**Issue by judewoolls** [A-SousaRodrigues/java-mini-project#2]
**USER STORY**: As a busy student i want to be able to have a text area to right some quick notes during online classes and with a clear submit button to add.

**Acceptance criteria**

- [ ] an input field that takes user text
- [ ] a submit button next to the text
- [ ] the button and input fields are styled

**Tasks**

- [ ] Create a HTML input field
- [ ] Add a HTML button
- [ ] Style using bootstrap
