### ISSUE TITLE
Note App #3: Modal

### ISSUE THREAD

**Issue by judewoolls** [A-SousaRodrigues/java-mini-project#9]
**USER STORY**: as a student who has lots of notes i want to be able to focus on a note

**Acceptance criteria**

- [ ] modal pops up to screen on note click
- [ ] the text from the note is displayed on the modal
- [ ] the modal closes

**Tasks**

- [ ] Create a modal using bootstrap/html
- [ ] Use event listeners and query selectors to get the text for that note
- [ ] display the text of the note onto the modal
